In [1]:
#pip install selenium

In [1]:
import numpy as np
import pandas as pd

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from time import sleep

In [13]:
#s=Service(r'C:\Users\lenovo\Assignment-1\chromedriver-win64\chromedriver-win64.exe')
driver=webdriver.Chrome()
driver.get("https://uk.investing.com/commodities/us-sugar-no11-historical-data")
#driver.maximize_window()

sleep(10)
ad_close=driver.find_element(By.XPATH,"(//button[@type='button'])[28]")
ad_close.click()
print("ADclosed")


time_frame = driver.find_element(By.XPATH,"//div[contains(@class, 'historical-data-v2_selection-arrow')]")
time_frame.click()

weekly=driver.find_element(By.XPATH,"//div[contains(@class, 'historical-data-v2_menu-row__oRAlf')][2]").click()
sleep(5)
table=driver.find_element(By.CLASS_NAME,'freeze-column-w-1')

headers = [header.text for header in table.find_elements(By.XPATH, './/thead//th')]
rows = []
for row in table.find_elements(By.XPATH, './/tbody//tr'):
    cells = [cell.text for cell in row.find_elements(By.XPATH, './/td')]
    if cells:
        rows.append(cells)

driver.quit()

ADclosed

In [16]:
df = pd.DataFrame(rows, columns=headers)
df

            Date  Price   Open   High    Low     Vol. Change %
0   Sep 15, 2024  21.14  18.98  21.39  18.84   88.67K  +11.20%
1   Sep 08, 2024  19.01  18.92  19.42  18.43   95.00K   +0.53%
2   Sep 01, 2024  18.91  19.12  19.77  18.84  241.06K   -2.43%
3   Aug 25, 2024  19.38  18.50  19.98  18.50  427.47K   +5.38%
4   Aug 18, 2024  18.39  18.00  18.43  17.52  223.06K   +2.00%
5   Aug 11, 2024  18.03  18.52  18.73  17.81  186.42K   -2.44%
6   Aug 04, 2024  18.48  18.05  18.88  17.65   42.03K   +2.10%
7   Jul 28, 2024  18.10  18.50  19.31  18.00   57.77K   -1.74%
8   Jul 21, 2024  18.42  18.66  18.74  17.86  302.00K   -1.29%
9   Jul 14, 2024  18.66  19.15  19.88  18.55  257.27K   -2.81%
10  Jul 07, 2024  19.20  20.13  20.37  19.18  270.32K   -4.67%
11  Jun 30, 2024  20.14  20.25  20.78  19.93  242.95K   -0.84%
12  Jun 23, 2024  20.31  18.92  20.33  18.82  187.68K   +7.06%
13  Jun 16, 2024  18.97  19.32  19.43  18.81  273.23K   -2.37%
14  Jun 09, 2024  19.43  18.95  19.64  18.59  426.43K   +2.26%
15  Jun 02, 2024  19.00  18.30  19.37  18.21  465.70K   +3.83%
16  May 26, 2024  18.30  18.67  18.80  18.03  219.17K   -0.60%
17  May 19, 2024  18.41  18.08  18.79  18.03  222.69K   +1.54%
18  May 12, 2024  18.13  19.24  19.34  17.95  292.38K   -6.06%
19  May 05, 2024  19.30  19.30  20.00  19.15  238.80K   +0.10%
20  Apr 28, 2024  19.28  19.37  20.23  19.09  153.33K   -0.62%
21  Apr 21, 2024  19.40  19.88  20.15  19.25  199.17K   -1.67%
22  Apr 14, 2024  19.73  20.51  20.60  19.17  246.37K   -3.52%
23  Apr 07, 2024  20.45  21.93  22.23  20.41  373.00K   -7.00%
24  Mar 31, 2024  21.99  22.65  22.91  21.80  297.50K   -2.35%
25  Mar 24, 2024  22.52  21.78  22.59  21.72  211.56K   +3.07%
26  Mar 17, 2024  21.85  22.20  22.35  21.13  220.73K   -1.22%
27  Mar 10, 2024  22.12  21.18  22.23  21.13  256.41K   +4.59%
28  Mar 03, 2024  21.15  21.13  21.68  20.53  257.49K   +0.28%
29  Feb 25, 2024  21.09  22.67  24.16  20.96  179.32K   -6.76%
30  Feb 18, 2024  22.62  23.00  23.08  22.11  140.48K   -1.99%
31  Feb 11, 2024  23.08  23.95  23.99  22.71  329.58K   -3.91%
32  Feb 04, 2024  24.02  23.94  24.42  23.02  397.11K   +0.54%
33  Jan 28, 2024  23.89  23.77  24.30  23.29  255.16K   +0.50%
34  Jan 21, 2024  23.77  23.56  24.62  23.25  289.81K   +0.85%
35  Jan 14, 2024  23.57  21.85  23.75  21.85  258.35K   +9.07%
36  Jan 07, 2024  21.61  21.11  21.96  21.11  234.54K   +2.37%
37  Dec 31, 2023  21.11  20.60  21.40  20.60  190.71K   +2.58%
38  Dec 24, 2023  20.58  20.60  21.91  20.03  198.02K   -0.19%
39  Dec 17, 2023  20.62  21.98  21.99  20.12  318.91K   -6.23%
40  Dec 10, 2023  21.99  23.44  23.49  21.16  443.00K   -5.86%
41  Dec 03, 2023  23.36  25.06  25.98  22.80  627.91K   -6.90%
42  Nov 26, 2023  25.09  26.98  27.30  24.95  468.03K   -7.01%
43  Nov 19, 2023  26.98  27.23  27.78  26.81  215.67K   -0.74%
44  Nov 12, 2023  27.18  27.30  27.81  27.00  238.31K   -0.40%
45  Nov 05, 2023  27.29  27.65  28.14  27.18  266.78K   -1.73%
46  Oct 29, 2023  27.77  27.50  27.83  26.65  263.57K   +1.57%
47  Oct 22, 2023  27.34  26.85  28.00  26.49  255.79K   +1.82%
48  Oct 15, 2023  26.85  27.09  27.67  26.80  235.59K   -0.67%
49  Oct 08, 2023  27.03  26.86  27.28  26.25  265.66K   +1.08%
50  Oct 01, 2023  26.74  26.54  26.83  25.28  311.02K   +1.79%
51  Sep 24, 2023  26.27  27.00  27.02  25.95  153.21K   -2.60%

In [37]:
clean=df
X=clean.drop(['High','Low','Vol.'],axis=1)
X

            Date  Price   Open Change %
0   Sep 15, 2024  21.14  18.98  +11.20%
1   Sep 08, 2024  19.01  18.92   +0.53%
2   Sep 01, 2024  18.91  19.12   -2.43%
3   Aug 25, 2024  19.38  18.50   +5.38%
4   Aug 18, 2024  18.39  18.00   +2.00%
5   Aug 11, 2024  18.03  18.52   -2.44%
6   Aug 04, 2024  18.48  18.05   +2.10%
7   Jul 28, 2024  18.10  18.50   -1.74%
8   Jul 21, 2024  18.42  18.66   -1.29%
9   Jul 14, 2024  18.66  19.15   -2.81%
10  Jul 07, 2024  19.20  20.13   -4.67%
11  Jun 30, 2024  20.14  20.25   -0.84%
12  Jun 23, 2024  20.31  18.92   +7.06%
13  Jun 16, 2024  18.97  19.32   -2.37%
14  Jun 09, 2024  19.43  18.95   +2.26%
15  Jun 02, 2024  19.00  18.30   +3.83%
16  May 26, 2024  18.30  18.67   -0.60%
17  May 19, 2024  18.41  18.08   +1.54%
18  May 12, 2024  18.13  19.24   -6.06%
19  May 05, 2024  19.30  19.30   +0.10%
20  Apr 28, 2024  19.28  19.37   -0.62%
21  Apr 21, 2024  19.40  19.88   -1.67%
22  Apr 14, 2024  19.73  20.51   -3.52%
23  Apr 07, 2024  20.45  21.93   -7.00%
24  Mar 31, 2024  21.99  22.65   -2.35%
25  Mar 24, 2024  22.52  21.78   +3.07%
26  Mar 17, 2024  21.85  22.20   -1.22%
27  Mar 10, 2024  22.12  21.18   +4.59%
28  Mar 03, 2024  21.15  21.13   +0.28%
29  Feb 25, 2024  21.09  22.67   -6.76%
30  Feb 18, 2024  22.62  23.00   -1.99%
31  Feb 11, 2024  23.08  23.95   -3.91%
32  Feb 04, 2024  24.02  23.94   +0.54%
33  Jan 28, 2024  23.89  23.77   +0.50%
34  Jan 21, 2024  23.77  23.56   +0.85%
35  Jan 14, 2024  23.57  21.85   +9.07%
36  Jan 07, 2024  21.61  21.11   +2.37%
37  Dec 31, 2023  21.11  20.60   +2.58%
38  Dec 24, 2023  20.58  20.60   -0.19%
39  Dec 17, 2023  20.62  21.98   -6.23%
40  Dec 10, 2023  21.99  23.44   -5.86%
41  Dec 03, 2023  23.36  25.06   -6.90%
42  Nov 26, 2023  25.09  26.98   -7.01%
43  Nov 19, 2023  26.98  27.23   -0.74%
44  Nov 12, 2023  27.18  27.30   -0.40%
45  Nov 05, 2023  27.29  27.65   -1.73%
46  Oct 29, 2023  27.77  27.50   +1.57%
47  Oct 22, 2023  27.34  26.85   +1.82%
48  Oct 15, 2023  26.85  27.09   -0.67%
49  Oct 08, 2023  27.03  26.86   +1.08%
50  Oct 01, 2023  26.74  26.54   +1.79%
51  Sep 24, 2023  26.27  27.00   -2.60%

In [46]:
X["product_name"]='Sugar'
product_cols=X.pop('Product_name')
X.insert(0,"Product_name",product_cols)

In [50]:
X.pop('product_name')

0     Sugar
1     Sugar
2     Sugar
3     Sugar
4     Sugar
5     Sugar
6     Sugar
7     Sugar
8     Sugar
9     Sugar
10    Sugar
11    Sugar
12    Sugar
13    Sugar
14    Sugar
15    Sugar
16    Sugar
17    Sugar
18    Sugar
19    Sugar
20    Sugar
21    Sugar
22    Sugar
23    Sugar
24    Sugar
25    Sugar
26    Sugar
27    Sugar
28    Sugar
29    Sugar
30    Sugar
31    Sugar
32    Sugar
33    Sugar
34    Sugar
35    Sugar
36    Sugar
37    Sugar
38    Sugar
39    Sugar
40    Sugar
41    Sugar
42    Sugar
43    Sugar
44    Sugar
45    Sugar
46    Sugar
47    Sugar
48    Sugar
49    Sugar
50    Sugar
51    Sugar
Name: product_name, dtype: object

In [51]:
X

   Product_name          Date  Price   Open Change %
0         Sugar  Sep 15, 2024  21.14  18.98  +11.20%
1         Sugar  Sep 08, 2024  19.01  18.92   +0.53%
2         Sugar  Sep 01, 2024  18.91  19.12   -2.43%
3         Sugar  Aug 25, 2024  19.38  18.50   +5.38%
4         Sugar  Aug 18, 2024  18.39  18.00   +2.00%
5         Sugar  Aug 11, 2024  18.03  18.52   -2.44%
6         Sugar  Aug 04, 2024  18.48  18.05   +2.10%
7         Sugar  Jul 28, 2024  18.10  18.50   -1.74%
8         Sugar  Jul 21, 2024  18.42  18.66   -1.29%
9         Sugar  Jul 14, 2024  18.66  19.15   -2.81%
10        Sugar  Jul 07, 2024  19.20  20.13   -4.67%
11        Sugar  Jun 30, 2024  20.14  20.25   -0.84%
12        Sugar  Jun 23, 2024  20.31  18.92   +7.06%
13        Sugar  Jun 16, 2024  18.97  19.32   -2.37%
14        Sugar  Jun 09, 2024  19.43  18.95   +2.26%
15        Sugar  Jun 02, 2024  19.00  18.30   +3.83%
16        Sugar  May 26, 2024  18.30  18.67   -0.60%
17        Sugar  May 19, 2024  18.41  18.08   +1.54%
18        Sugar  May 12, 2024  18.13  19.24   -6.06%
19        Sugar  May 05, 2024  19.30  19.30   +0.10%
20        Sugar  Apr 28, 2024  19.28  19.37   -0.62%
21        Sugar  Apr 21, 2024  19.40  19.88   -1.67%
22        Sugar  Apr 14, 2024  19.73  20.51   -3.52%
23        Sugar  Apr 07, 2024  20.45  21.93   -7.00%
24        Sugar  Mar 31, 2024  21.99  22.65   -2.35%
25        Sugar  Mar 24, 2024  22.52  21.78   +3.07%
26        Sugar  Mar 17, 2024  21.85  22.20   -1.22%
27        Sugar  Mar 10, 2024  22.12  21.18   +4.59%
28        Sugar  Mar 03, 2024  21.15  21.13   +0.28%
29        Sugar  Feb 25, 2024  21.09  22.67   -6.76%
30        Sugar  Feb 18, 2024  22.62  23.00   -1.99%
31        Sugar  Feb 11, 2024  23.08  23.95   -3.91%
32        Sugar  Feb 04, 2024  24.02  23.94   +0.54%
33        Sugar  Jan 28, 2024  23.89  23.77   +0.50%
34        Sugar  Jan 21, 2024  23.77  23.56   +0.85%
35        Sugar  Jan 14, 2024  23.57  21.85   +9.07%
36        Sugar  Jan 07, 2024  21.61  21.11   +2.37%
37        Sugar  Dec 31, 2023  21.11  20.60   +2.58%
38        Sugar  Dec 24, 2023  20.58  20.60   -0.19%
39        Sugar  Dec 17, 2023  20.62  21.98   -6.23%
40        Sugar  Dec 10, 2023  21.99  23.44   -5.86%
41        Sugar  Dec 03, 2023  23.36  25.06   -6.90%
42        Sugar  Nov 26, 2023  25.09  26.98   -7.01%
43        Sugar  Nov 19, 2023  26.98  27.23   -0.74%
44        Sugar  Nov 12, 2023  27.18  27.30   -0.40%
45        Sugar  Nov 05, 2023  27.29  27.65   -1.73%
46        Sugar  Oct 29, 2023  27.77  27.50   +1.57%
47        Sugar  Oct 22, 2023  27.34  26.85   +1.82%
48        Sugar  Oct 15, 2023  26.85  27.09   -0.67%
49        Sugar  Oct 08, 2023  27.03  26.86   +1.08%
50        Sugar  Oct 01, 2023  26.74  26.54   +1.79%
51        Sugar  Sep 24, 2023  26.27  27.00   -2.60%

In [54]:
X.rename(columns={'Date':'Product_Date'},inplace=True)

In [55]:
X

   Product_name  Product_Date  Price   Open Change %
0         Sugar  Sep 15, 2024  21.14  18.98  +11.20%
1         Sugar  Sep 08, 2024  19.01  18.92   +0.53%
2         Sugar  Sep 01, 2024  18.91  19.12   -2.43%
3         Sugar  Aug 25, 2024  19.38  18.50   +5.38%
4         Sugar  Aug 18, 2024  18.39  18.00   +2.00%
5         Sugar  Aug 11, 2024  18.03  18.52   -2.44%
6         Sugar  Aug 04, 2024  18.48  18.05   +2.10%
7         Sugar  Jul 28, 2024  18.10  18.50   -1.74%
8         Sugar  Jul 21, 2024  18.42  18.66   -1.29%
9         Sugar  Jul 14, 2024  18.66  19.15   -2.81%
10        Sugar  Jul 07, 2024  19.20  20.13   -4.67%
11        Sugar  Jun 30, 2024  20.14  20.25   -0.84%
12        Sugar  Jun 23, 2024  20.31  18.92   +7.06%
13        Sugar  Jun 16, 2024  18.97  19.32   -2.37%
14        Sugar  Jun 09, 2024  19.43  18.95   +2.26%
15        Sugar  Jun 02, 2024  19.00  18.30   +3.83%
16        Sugar  May 26, 2024  18.30  18.67   -0.60%
17        Sugar  May 19, 2024  18.41  18.08   +1.54%
18        Sugar  May 12, 2024  18.13  19.24   -6.06%
19        Sugar  May 05, 2024  19.30  19.30   +0.10%
20        Sugar  Apr 28, 2024  19.28  19.37   -0.62%
21        Sugar  Apr 21, 2024  19.40  19.88   -1.67%
22        Sugar  Apr 14, 2024  19.73  20.51   -3.52%
23        Sugar  Apr 07, 2024  20.45  21.93   -7.00%
24        Sugar  Mar 31, 2024  21.99  22.65   -2.35%
25        Sugar  Mar 24, 2024  22.52  21.78   +3.07%
26        Sugar  Mar 17, 2024  21.85  22.20   -1.22%
27        Sugar  Mar 10, 2024  22.12  21.18   +4.59%
28        Sugar  Mar 03, 2024  21.15  21.13   +0.28%
29        Sugar  Feb 25, 2024  21.09  22.67   -6.76%
30        Sugar  Feb 18, 2024  22.62  23.00   -1.99%
31        Sugar  Feb 11, 2024  23.08  23.95   -3.91%
32        Sugar  Feb 04, 2024  24.02  23.94   +0.54%
33        Sugar  Jan 28, 2024  23.89  23.77   +0.50%
34        Sugar  Jan 21, 2024  23.77  23.56   +0.85%
35        Sugar  Jan 14, 2024  23.57  21.85   +9.07%
36        Sugar  Jan 07, 2024  21.61  21.11   +2.37%
37        Sugar  Dec 31, 2023  21.11  20.60   +2.58%
38        Sugar  Dec 24, 2023  20.58  20.60   -0.19%
39        Sugar  Dec 17, 2023  20.62  21.98   -6.23%
40        Sugar  Dec 10, 2023  21.99  23.44   -5.86%
41        Sugar  Dec 03, 2023  23.36  25.06   -6.90%
42        Sugar  Nov 26, 2023  25.09  26.98   -7.01%
43        Sugar  Nov 19, 2023  26.98  27.23   -0.74%
44        Sugar  Nov 12, 2023  27.18  27.30   -0.40%
45        Sugar  Nov 05, 2023  27.29  27.65   -1.73%
46        Sugar  Oct 29, 2023  27.77  27.50   +1.57%
47        Sugar  Oct 22, 2023  27.34  26.85   +1.82%
48        Sugar  Oct 15, 2023  26.85  27.09   -0.67%
49        Sugar  Oct 08, 2023  27.03  26.86   +1.08%
50        Sugar  Oct 01, 2023  26.74  26.54   +1.79%
51        Sugar  Sep 24, 2023  26.27  27.00   -2.60%

In [62]:
X['Product_Date']=pd.to_datetime(X['Product_Date'],format='%d-%m-%Y')
X.head()

  Product_name Product_Date  Price   Open Change %
0        Sugar   2024-09-15  21.14  18.98  +11.20%
1        Sugar   2024-09-08  19.01  18.92   +0.53%
2        Sugar   2024-09-01  18.91  19.12   -2.43%
3        Sugar   2024-08-25  19.38  18.50   +5.38%
4        Sugar   2024-08-18  18.39  18.00   +2.00%

In [64]:
X['DAY'] = X['Product_Date'].dt.day_name()
X.head()

  Product_name Product_Date  Price   Open Change %     DAY
0        Sugar   2024-09-15  21.14  18.98  +11.20%  Sunday
1        Sugar   2024-09-08  19.01  18.92   +0.53%  Sunday
2        Sugar   2024-09-01  18.91  19.12   -2.43%  Sunday
3        Sugar   2024-08-25  19.38  18.50   +5.38%  Sunday
4        Sugar   2024-08-18  18.39  18.00   +2.00%  Sunday

In [77]:
import requests
api_url = 'https://api.exchangerate-api.com/v4/latest/USD'
response = requests.get(api_url)
data = response.json()

X['Price'] = X['Price'].replace({'\$': ''}, regex=True).astype(float)

usd_to_inr_rate = data['rates']['INR']

X['Final Price (INR)'] = X['Price'] * usd_to_inr_rate

In [78]:
X.head()

  Product_name Product_Date  Price   Open Change %     DAY  Final Price (INR)
0        Sugar   2024-09-15  21.14  18.98  +11.20%  Sunday          1770.0522
1        Sugar   2024-09-08  19.01  18.92   +0.53%  Sunday          1591.7073
2        Sugar   2024-09-01  18.91  19.12   -2.43%  Sunday          1583.3343
3        Sugar   2024-08-25  19.38  18.50   +5.38%  Sunday          1622.6874
4        Sugar   2024-08-18  18.39  18.00   +2.00%  Sunday          1539.7947

In [82]:
output=X.drop(['Change %','Price','Open'],axis=1)

In [87]:
output

   Product_name Product_Date     DAY  Final Price (INR)
0         Sugar   2024-09-15  Sunday          1770.0522
1         Sugar   2024-09-08  Sunday          1591.7073
2         Sugar   2024-09-01  Sunday          1583.3343
3         Sugar   2024-08-25  Sunday          1622.6874
4         Sugar   2024-08-18  Sunday          1539.7947
5         Sugar   2024-08-11  Sunday          1509.6519
6         Sugar   2024-08-04  Sunday          1547.3304
7         Sugar   2024-07-28  Sunday          1515.5130
8         Sugar   2024-07-21  Sunday          1542.3066
9         Sugar   2024-07-14  Sunday          1562.4018
10        Sugar   2024-07-07  Sunday          1607.6160
11        Sugar   2024-06-30  Sunday          1686.3222
12        Sugar   2024-06-23  Sunday          1700.5563
13        Sugar   2024-06-16  Sunday          1588.3581
14        Sugar   2024-06-09  Sunday          1626.8739
15        Sugar   2024-06-02  Sunday          1590.8700
16        Sugar   2024-05-26  Sunday          1532.2590
17        Sugar   2024-05-19  Sunday          1541.4693
18        Sugar   2024-05-12  Sunday          1518.0249
19        Sugar   2024-05-05  Sunday          1615.9890
20        Sugar   2024-04-28  Sunday          1614.3144
21        Sugar   2024-04-21  Sunday          1624.3620
22        Sugar   2024-04-14  Sunday          1651.9929
23        Sugar   2024-04-07  Sunday          1712.2785
24        Sugar   2024-03-31  Sunday          1841.2227
25        Sugar   2024-03-24  Sunday          1885.5996
26        Sugar   2024-03-17  Sunday          1829.5005
27        Sugar   2024-03-10  Sunday          1852.1076
28        Sugar   2024-03-03  Sunday          1770.8895
29        Sugar   2024-02-25  Sunday          1765.8657
30        Sugar   2024-02-18  Sunday          1893.9726
31        Sugar   2024-02-11  Sunday          1932.4884
32        Sugar   2024-02-04  Sunday          2011.1946
33        Sugar   2024-01-28  Sunday          2000.3097
34        Sugar   2024-01-21  Sunday          1990.2621
35        Sugar   2024-01-14  Sunday          1973.5161
36        Sugar   2024-01-07  Sunday          1809.4053
37        Sugar   2023-12-31  Sunday          1767.5403
38        Sugar   2023-12-24  Sunday          1723.1634
39        Sugar   2023-12-17  Sunday          1726.5126
40        Sugar   2023-12-10  Sunday          1841.2227
41        Sugar   2023-12-03  Sunday          1955.9328
42        Sugar   2023-11-26  Sunday          2100.7857
43        Sugar   2023-11-19  Sunday          2259.0354
44        Sugar   2023-11-12  Sunday          2275.7814
45        Sugar   2023-11-05  Sunday          2284.9917
46        Sugar   2023-10-29  Sunday          2325.1821
47        Sugar   2023-10-22  Sunday          2289.1782
48        Sugar   2023-10-15  Sunday          2248.1505
49        Sugar   2023-10-08  Sunday          2263.2219
50        Sugar   2023-10-01  Sunday          2238.9402
51        Sugar   2023-09-24  Sunday          2199.5871

In [88]:
price_col=X['Price']
output.insert(1,"price",price_col)

In [89]:
output.head()

  Product_name  price Product_Date     DAY  Final Price (INR)
0        Sugar  21.14   2024-09-15  Sunday          1770.0522
1        Sugar  19.01   2024-09-08  Sunday          1591.7073
2        Sugar  18.91   2024-09-01  Sunday          1583.3343
3        Sugar  19.38   2024-08-25  Sunday          1622.6874
4        Sugar  18.39   2024-08-18  Sunday          1539.7947

In [90]:
output

   Product_name  price Product_Date     DAY  Final Price (INR)
0         Sugar  21.14   2024-09-15  Sunday          1770.0522
1         Sugar  19.01   2024-09-08  Sunday          1591.7073
2         Sugar  18.91   2024-09-01  Sunday          1583.3343
3         Sugar  19.38   2024-08-25  Sunday          1622.6874
4         Sugar  18.39   2024-08-18  Sunday          1539.7947
5         Sugar  18.03   2024-08-11  Sunday          1509.6519
6         Sugar  18.48   2024-08-04  Sunday          1547.3304
7         Sugar  18.10   2024-07-28  Sunday          1515.5130
8         Sugar  18.42   2024-07-21  Sunday          1542.3066
9         Sugar  18.66   2024-07-14  Sunday          1562.4018
10        Sugar  19.20   2024-07-07  Sunday          1607.6160
11        Sugar  20.14   2024-06-30  Sunday          1686.3222
12        Sugar  20.31   2024-06-23  Sunday          1700.5563
13        Sugar  18.97   2024-06-16  Sunday          1588.3581
14        Sugar  19.43   2024-06-09  Sunday          1626.8739
15        Sugar  19.00   2024-06-02  Sunday          1590.8700
16        Sugar  18.30   2024-05-26  Sunday          1532.2590
17        Sugar  18.41   2024-05-19  Sunday          1541.4693
18        Sugar  18.13   2024-05-12  Sunday          1518.0249
19        Sugar  19.30   2024-05-05  Sunday          1615.9890
20        Sugar  19.28   2024-04-28  Sunday          1614.3144
21        Sugar  19.40   2024-04-21  Sunday          1624.3620
22        Sugar  19.73   2024-04-14  Sunday          1651.9929
23        Sugar  20.45   2024-04-07  Sunday          1712.2785
24        Sugar  21.99   2024-03-31  Sunday          1841.2227
25        Sugar  22.52   2024-03-24  Sunday          1885.5996
26        Sugar  21.85   2024-03-17  Sunday          1829.5005
27        Sugar  22.12   2024-03-10  Sunday          1852.1076
28        Sugar  21.15   2024-03-03  Sunday          1770.8895
29        Sugar  21.09   2024-02-25  Sunday          1765.8657
30        Sugar  22.62   2024-02-18  Sunday          1893.9726
31        Sugar  23.08   2024-02-11  Sunday          1932.4884
32        Sugar  24.02   2024-02-04  Sunday          2011.1946
33        Sugar  23.89   2024-01-28  Sunday          2000.3097
34        Sugar  23.77   2024-01-21  Sunday          1990.2621
35        Sugar  23.57   2024-01-14  Sunday          1973.5161
36        Sugar  21.61   2024-01-07  Sunday          1809.4053
37        Sugar  21.11   2023-12-31  Sunday          1767.5403
38        Sugar  20.58   2023-12-24  Sunday          1723.1634
39        Sugar  20.62   2023-12-17  Sunday          1726.5126
40        Sugar  21.99   2023-12-10  Sunday          1841.2227
41        Sugar  23.36   2023-12-03  Sunday          1955.9328
42        Sugar  25.09   2023-11-26  Sunday          2100.7857
43        Sugar  26.98   2023-11-19  Sunday          2259.0354
44        Sugar  27.18   2023-11-12  Sunday          2275.7814
45        Sugar  27.29   2023-11-05  Sunday          2284.9917
46        Sugar  27.77   2023-10-29  Sunday          2325.1821
47        Sugar  27.34   2023-10-22  Sunday          2289.1782
48        Sugar  26.85   2023-10-15  Sunday          2248.1505
49        Sugar  27.03   2023-10-08  Sunday          2263.2219
50        Sugar  26.74   2023-10-01  Sunday          2238.9402
51        Sugar  26.27   2023-09-24  Sunday          2199.5871

In [91]:
output.isnull()

    Product_name  price  Product_Date    DAY  Final Price (INR)
0          False  False         False  False              False
1          False  False         False  False              False
2          False  False         False  False              False
3          False  False         False  False              False
4          False  False         False  False              False
5          False  False         False  False              False
6          False  False         False  False              False
7          False  False         False  False              False
8          False  False         False  False              False
9          False  False         False  False              False
10         False  False         False  False              False
11         False  False         False  False              False
12         False  False         False  False              False
13         False  False         False  False              False
14         False  False         False  False              False
15         False  False         False  False              False
16         False  False         False  False              False
17         False  False         False  False              False
18         False  False         False  False              False
19         False  False         False  False              False
20         False  False         False  False              False
21         False  False         False  False              False
22         False  False         False  False              False
23         False  False         False  False              False
24         False  False         False  False              False
25         False  False         False  False              False
26         False  False         False  False              False
27         False  False         False  False              False
28         False  False         False  False              False
29         False  False         False  False              False
30         False  False         False  False              False
31         False  False         False  False              False
32         False  False         False  False              False
33         False  False         False  False              False
34         False  False         False  False              False
35         False  False         False  False              False
36         False  False         False  False              False
37         False  False         False  False              False
38         False  False         False  False              False
39         False  False         False  False              False
40         False  False         False  False              False
41         False  False         False  False              False
42         False  False         False  False              False
43         False  False         False  False              False
44         False  False         False  False              False
45         False  False         False  False              False
46         False  False         False  False              False
47         False  False         False  False              False
48         False  False         False  False              False
49         False  False         False  False              False
50         False  False         False  False              False
51         False  False         False  False              False

In [93]:
output.to_excel('output.xlsx', index=False)